function encode = ConditionTriggerEncode

%%% Task - specific

%%
global specs cache

%%
encode = [];

encode = [encode ...
    specs.Encodes.COND_SEMAPHORE ...
    specs.Encodes.COND_SEMAPHORE ...
    specs.Encodes.COND_SEMAPHORE ...
    cache.trial.Conditions.RuleImages.Group ...
    cache.trial.Conditions.RuleImages.Cue ...
    cache.trial.Conditions.RuleImages.Stim ...
    specs.Encodes.VAR_SEMAPHORE ...
    cache.trial.Conditions.Sequence ...
    specs.Encodes.VAR_SEMAPHORE ...
    specs.Encodes.COND_SEMAPHORE ...
    specs.Encodes.COND_SEMAPHORE ...
    specs.Encodes.COND_SEMAPHORE];