function GuiStats

%%% Task - specific

%%
global stats figures

tag = 'statstext';

delete(findobj(figures.Gui.h,'Tag',tag));

str = {sprintf('Trial %d - Block %d',stats.TrialNo,stats.BlockNo) ...
        sprintf('Correct Trials: %.0f/%.0f (%.2f)',stats.CorrectTrials,stats.AttemptedTrials,stats.Accuracy) ...
        sprintf('Broken Trials: %.0f (%.2f)',stats.BreakFixTrials,stats.BreakFixRate) ...
        sprintf('Reward drops: %.0f',stats.NumRewards) ...
        sprintf('Running Time: %.1f', stats.RunningTime) ...
        sprintf('Idle Time: %.1f', stats.IdleTime)};

statstext = uicontrol(figures.Gui.h,'Style','text', ...
                'Tag',tag, ...
                'String',str, ...
                'Position',[724 495 160 155], ...
                'HorizontalAlignment','left', ...
                'FontSize',8);
drawnow;