function MailAdd( message , attachment , recipient )

global specs devs
    

devs.Mail.Queue = [devs.Mail.Queue ...
            struct('Title', sprintf('%s - %s', ...
                                        specs.Version.Monkey, ...
                                        specs.Version.ScriptRun), ...
                                        ... %datestr(date)), ... %datestr(datetime('now'))), ...
                   'Body', message, ...
                   'Attachment', attachment, ...
                   'Recipient', recipient)];